- name: create all params
  hosts: localhost
  tasks:
    - name: install botocore and boto3 for aws ssm dependency
      ansible.builtin.pip:
        name: "{{item}}"
        executable: pip3
      loop:
        - botocore
        - boto3
    - name: create ssm parameters using shell module
      ansible.builtin.shell: aws ssm put-parameter --name "{{item.key}}" --type "String" --value "{{item.value}}" --overwrite
      loop:
       - {key: "mutable.cart.dev.CATALOGUE_HOST", value: "catalogue-dev.roboshop.ppk"}
       - {key: "mutable.cart.dev.REDIS_HOST", value: "redis-dev.roboshop.ppk"}
       - {key: "mutable.catalogue.dev.MONGO", value: "true"}
       - {key: "mutable.catalogue.dev.MONGO_URL", value: "mongodb://mongodb-dev.roboshop.ppk:27017/catalogue"}
       - {key: "mutable.payment.dev.CART_HOST", value: "cart-dev.roboshop.ppk"}
       - {key: "mutable.payment.dev.USER_HOST", value: "user-dev.roboshop.ppk"}
       - {key: "mutable.payment.dev.AMQP_HOST", value: "rabbitmq-dev.roboshop.ppk"}
       - {key: "mutable.payment.dev.AMQP_USER", value: "roboshop"}
       - {key: "mutable.payment.dev.AMQP_PASS", value: "roboshop123"}
       - {key: "mutable.mysql.dev.MYSQL_PASSWORD", value: "RoboShop@1"}
       - {key: "mutable.rabbitmq.dev.RABBITMQ_PASSWORD", value: "roboshop123"}
       - {key: "mutable.shipping.dev.CART_ENDPOINT", value: "cart-dev.roboshop.ppk:8080"}
       - {key: "mutable.shipping.dev.DB_HOST", value: "mysql-dev.roboshop.ppk"}
       - {key: "mutable.user.dev.MONGO", value: "true"}
       - {key: "mutable.user.dev.REDIS_HOST", value: "redis-dev.roboshop.ppk"}
       - {key: "mutable.user.dev.MONGO_URL", value: "mongodb://mongodb-dev.roboshop.ppk:27017/users"}